import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import Provider from "./provider"
import "./globals.css";

const outfit = Outfit({subsets: ['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
      >
        <Provider>
          {children}
        </Provider>
        
      </body>
    </html>
  );
}
